version: 2
jobs:
  shops-staging:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Deploy Shop Frontend
          command: ssh -o "StrictHostKeyChecking no" ubuntu@ec2-3-17-6-220.us-east-2.compute.amazonaws.com "cd ~/app/shop; git checkout clicknshop; yarn install --production; sudo rm -rf build; yarn build; sudo cp -r build/* /var/www/shop.woozeee.com/"

workflows:
  version: 2

  staging:
    jobs:
      # Staging
      - shops-staging:
          filters:
            branches:
              only: clicknshop
